title: <p align="center"> Achin Das </p>
logo: assets/img/Profile-1.png

description:
  <p align="center">
  <a href="doc/Achin%20Das%20-%20Brief%20Profile.pdf">Resume</a> |
  <a href="http://linkedin.com/in/achin-das-044560">LinkedIn</a> |
  <a href="https://github.com/achindas">GitHub</a>
  
  <br>   
  Senior IT Application Delivery Leader passionate about building applications using
  open-source stack on microservices architecture enriched by AI/ML.
  <br>
  </p>


theme: jekyll-theme-minimal
